#!/bin/bash

#SBATCH --reservation hpc-courses-bio-501-2024
#SBATCH --job-name="TF versus Eaa, Ead"
#SBATCH --nodes 1
#SBATCH --ntasks-per-core 1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu 1024
#SBATCH --time 10:00:00
#SBATCH --output out-%J.txt
#SBATCH --error err-%J.txt


 python3 MC_simulation_protein_A
wait
